language: python

cache: pip

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - name: "lint"
      python: 3.8
      install:
      script:
        - black --check .
        - flake8 altair_data_server
        - mypy altair_data_server

env:
  global:
    - TEST_DIR=/tmp/_altair_data_server/

before_install:
  - pip install pip --upgrade
  - pip install -r requirements_dev.txt

install:
  - pip install -e .

script:
  - mkdir -p $TEST_DIR
  - cd $TEST_DIR && python -m pytest --pyargs altair_data_server
