language: python

cache: pip
  
# Enable 3.7 without globally enabling sudo and xenial
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
    - TEST_DIR=/tmp/_altair_data_server/

before_install:
  - pip install pip --upgrade;

install:
  - pip install .;

script:
  - mkdir -p $TEST_DIR
  - cd $TEST_DIR && python -m pytest --pyargs altair_data_server;
